### ISSUE TITLE
document the API that parks needs so BCE can do it's thing

### ISSUE THREAD

**Issue by monkeypants** [gs-gs/parks-bce-integration-bookable-things#1]
So that BCE users can plan a school excursion to Canberra
they need to check the availability of various bookable things at ANBG
using the "check availability" API

...

**Comment by monkeypants** [comment]
When BCE has a "pending" booking in their system,
then need to somehow notify ANBG
so they log in and process it (accept or decline)

Is this an API thing or do you use email, etc?

**Comment by monkeypants** [comment]
When a a BCE booking is complete,
they need to notify ANBG by calling some kind of "booking done" API,
so that ANBG can:
 * issue an invoice
 * send any follow-up survey, etc

**Comment by monkeypants** [comment]
At some point when the data is available, BCE needs to send detailed information about a completed booking to ANBG using some kind of "detailed information about the booking API"

**Comment by monkeypants** [comment]
Do we need anything more than that?

**Comment by simon-tma** [comment]
We need to be able to get the list of resources so that the spaces in BCE can be mapped to them, so we know which resources to check the availability of.

**Comment by monkeypants** [comment]
OK, how's this rough sketch:
* `GET /parks/ANBG/bookables/` (returns a summary list of bookable things at ANBG)
* `GET /parks/ANBG/bookables/{id}` (info about the individual bookable thing)
* `GET /parks/ANBG/bookables/{id}/availability?from=$date&to=$date` (list of time periods in that date range that may be booked). This is the thing you poll to maintain your cache.
* `POST {booking_details} /parks/bookables/{id}/pending` creates a pending booking; error if not available. Returns a `/parks/ANBG/bookings/{id}` link when it works (note, "bookable" vs "booking"; probably need some better word-choosing).
* `POST {finalisation} /bookings/{id}/completion` tells ANBG they can issue invoice and so-on.
* `POST {extra_info} /bookings/{id}/details` sends the detailed information about the finalised booking
* `PUT {extra_info} /bookings/{id}/details` modifies the detailed information about the finalised booing

Do you also need something like `DELETE /parks/bookings/{id}/` (or `POST {reason} /parks/bookables/{id}/caccelation`)?

**Comment by monkeypants** [comment]
note about permissions:
* if you created the booking (`POST /parks/ANBG/bookables/{id}/pending`) then you can GET the `/parks/bookings/{id}` (and POST/PUT the subresources), else 4xx
* when you `GET /parks/ANBG/bookables/{id}/availability` you don't get any info about why it's not bookable when it isn't.

**Comment by monkeypants** [comment]
Do you have an API (going the other way; Parks makes a call against BCE) to fetch a list of pending bookings that you know about? I was wondering about eventual consistency in the case where you thought we had a pending booking but didn't.

**Comment by monkeypants** [comment]
Also, please check the new docs at https://parks-australia-bookable-things.readthedocs.io/ (work in progress, obviously).

**Comment by monkeypants** [comment]
pinging @koriaf, @mr-love, @dormerod, FYI please be aware of this conversation...

**Comment by mr-love** [comment]
On the parks side I believe they don't issue an invoice until they have the actual numbers of students on the day. So I guess the staff would use the parks patrol app to update the numbers with `PUT {extra_info} /bookings/{id}/details` and then need an endpoint similar to `POST {finalisation} /bookings/{id}/completion` to send the invoice off. 

~~Do we have an idea of what a time periods look like for `availability?from=$date&to=$date (list of time periods in that date range that may be booked).` I assume a list of (from datetime - to datetime) is all that's needed.~~ -edit- I see it in the logical model.

> - POST {booking_details} /parks/bookables/{id}/pending creates a pending booking; error if not available. Returns a /parks/ANBG/bookings/{id} link when it works (note, "bookable" vs "booking"; probably need some better word-choosing).

Do we need to put that on the bookables resource path? Why not just a post to `/parks/ANBG/bookings/` with some booking parameter for pending vs confirmed

**Comment by koriaf** [comment]
> Do we need to put that on the bookables resource path? Why not just a post to /parks/ANBG/bookings/ with some booking parameter for pending vs confirmed

it's just a question of approaches, where do we store these parameters. In the Chris's version they are stored in urls; or it could be the same urls with  {"action": "create", ...}, or {"action": "finalize"} and so on. There is not correct way here :-)
It's like `POST {booking_details} /parks/bookables/{id}/pending` could be `POST {info} /parks/bookables/{id}/reservation/`; then return reservation ID as `/parks/reservations/{id}` or POST `/parks/reservations/` with bookable ID in the request (as Mark offers) and retrieve them as `/parks/reservations/{reservation_id}`... I feel that described urls structure is something in between REST and RPC style and not purely either of them. Although it would bear it's role.

Regarding naming confusing of bookable and booking - it would be wonderful to rename something. It could be amentity vs booking or bookable vs reservation.

I have no problems with the API in general, but there might be some changes we get once we start to implement it - so, given the API size (it's not so big), we might be better to implement it completely before users will start to implement their part to find these problems.

**Comment by koriaf** [comment]
After reading the documentation I have next notes:
1. ` GET /parks/(str:park-slug)/bookables?team=(org-slug)` - why do we have one parameter in URL but another in the request GET? Is it ever possible that requester has access to 2 parks? Why not `GET /bookables/?park={slug}&team={name}` with the parameters optional?
2. ` GET /parks/(str:park-slug)/bookables/(int: id)?from=(date: from_date)&until=(date: to_date)` - the same is applicable, the bookable is probably has only one park, so we don't need it here; URL `/bookable/{id}/availability/?from=&till=&` will be easier. So my proposition so far is to remove parks_slug from all urls, leaving it as GET filter parameter for the bookable list (optional) and in fact any further work will require only bookable ID, not the park slug - so adding it to the URL is just a extra visual load.
3. `POST {booking_details} /parks/bookables/{id}/pending` vs `POST {detals with bookable ID in it} /reservations/` - the second will be more REST I guess, but not sure, it's really matter of preference
4. `PATCH /reservations/{id}/` with:
   * status - finalized, cancelled, etc - some statuses may require some extra fields passed as well
   * number of students (new data)
   * updated old data (number of guides, etc)
This PATCH approach will be logical from the technical point of view, because any data passed to the API will be stored in some fields of the Reservation object, so why invent extra layers instead of just giving a way to do it.

Also let's assume that base API url will change (in fact will be something like https://trade.parksaustralia.gov.au/api/reservation/v1/{url}) and by saying "/reservations" I mean https://trade.parksaustralia.gov.au/api/reservation/v1/reservations/

Wording: why don't we call api BookablesApi and use worlds Amenities or something and bookings are just Reservations. It's a question to the native speakers, but definitely should be thought about. Or call the whole api The Reservations Api V1 and objects `Things` and `Bookings`.

The `/reservations/` url could be `/bookable/{bookable_id}/reservations/` as well, which shows us nice structure in our urls or could be not. It will require client to store pair of (bookable_id, reservation_id) instead of just reservation_id, but I think it's not a big deal. This is also question of preferences.

**Comment by monkeypants** [comment]
@mr-love 
>> POST {booking_details} /parks/bookables/{id}/pending creates a pending booking; error if not available. Returns a /parks/ANBG/bookings/{id} link when it works (note, "bookable" vs "booking"; probably need some better word-choosing).
>
> Do we need to put that on the bookables resource path? Why not just a post to /parks/ANBG/bookings/ with some booking parameter for pending vs confirmed

That would work too, it's probably better.

**Comment by monkeypants** [comment]
@koriaf
> why do we have one parameter in URL but another in the request GET?
> Is it ever possible that requester has access to 2 parks?
> Why not GET /bookables/?park={slug}&team={name} with the parameters optional?

No good reason, it was just a 'rough sketch' :) I'm glad it got you thinking about better designs.

More generally (danger, generalising beyond the current BCE requirement):
 * agents that make bookings could be parks orgs (eCommerce site, visitors centre POS, rangers using apps), the existing RSA network, or marketing channels / platforms such as BCE (or travel agent cartels, etc).
 * delivery orgs that provide bookable things may be parks orgs (such as the ANBG education unit, or ranger groups that provide Ranger Guided Tours, or parks orgs that manage campgrounds, etc), or the existing CTO network.
* the bookable things could be diverse. In the current example (ANBG / BCE integration), I think they are "education experiences" (including a guide) or an "education resource" (not including a guide), e.g. greenhouses or ponds at the ANBG. But in the future they would include campgrounds, or limited numbers of bushwalkers in an ecologically sensitive area (more like a permit), or ranger-guided tours, or even commercial tours offered by CTOs.

The long-game here is to support CTOs as well as Parks Staff. As the parks re-open after COVID-19 (or after the Fires before that - some were already closed before the biosecurity restrictions), we want to be able to direct "deal flow" (customers) to the CTOs, and we want RSAs to be able to do that too. That's our way of stimulating the tourism economy  around parks, beyond the usual "Taste of Kakadu" promotions (etc). This is why the general case deserves some thought, but our goal is to deliver BCE integration in a straitforward way that doesn't make the general case harder.

**Comment by monkeypants** [comment]
@dormerod, FYI - I plan to:
* close this ticket when requirements.rst captures the features we need as stories.
* raise new ticket(s) about consultation with TMA/BCE about the requirements. This may result in changes to requirements.rst
* document api.rst using endpoint names (rather than URLs) in the diagrams, so the `.. http` directives (in that file) become the only place we specify URL patterns. This will allow us to iterate the 
URL patterns until they are right.

**Comment by koriaf** [comment]
I like that generalized approach you have mentioned. Let's just develop it having BCE integration in mind, so it exactly fits their requirements, but building it in a way that theoretically allow other organisations to use it if their case fits as well.

I think I'm fine with the current state of requirements in general, and it's just urls and these technical REST api details which I see differently - but it's normal. I could write the urls structure which will make me happy for the current stage and you approve it and merge to your current documentation.

**Comment by monkeypants** [comment]
Yes, please start building the API. Ready/fire/aim, before the specs are written. Presumably we can tweak the url design if it's not working for BCE.

**Comment by koriaf** [comment]
I think we could close that task because the work has started in other tasks in the another repo
