### ISSUE TITLE
add price_schedule attribute to bookable thing

### ISSUE THREAD

**Issue by monkeypants** [gs-gs/parks-bce-integration-bookable-things#12]
Currently, when I query like this:

```
GET /products/?org_id=(org_id)&org_slug=(string)&park_slug=(park_slug)&is_archived=true/false/all
```

I get a response like this:

```
{
  "count": 2,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 2,
      "type": "park",
      "park": "kakadu",
      "delivery_org": "Bowali",
      "name": "Naidoc Week",
      "short_description": "",
      "image": "http://localhost:8000/media/products_images/ObQOeL8uJqY.jpg",
      "contact": "",
      "unit": "person",
      "cost_per_unit": "6.00",
      "is_archived": false,
    },
  ]
}
```

Note, it contains a single "cost_per_unit" attribute.

Here's the problem:
```
As a Park Manager
I need to schedule price changes for bookable things
So that people pay the correct price for future bookings, even when prices change 
```

In other words, the park needs to be able to do things like "as of 2020/01/01, the new price will be ...".

The `cost_per_unit` attribute is still OK to have, as-of now. But we need to tell the API user what the price will be at some point in the future. Suggested design is to have a new attribute like this

```
{
   ...
   cost_per_unit: "6.0",
   price_schedule: {
      "20200101": "6.0",
      "20210101": "7.0",
      "20220101": "8.0",
      "20230101": "9.0",
   }
}
```

So to calculate the price on any given day, the API user can use the price of the highest date on or before the date of the booking.

**Comment by dormerod** [comment]
SGTM :)

What do you think @simon-tma?

**Comment by simon-tma** [comment]
This is looking good. I'm assuming the `POST`/`PATCH` bodies will use the same structure.

It's just missing the starting price. Could either use a special key (`default`?) or just have the price be `0` until the first scheduled value.

**Comment by koriaf** [comment]
documented in the https://parks-australia-bookable-things.readthedocs.io/en/latest/api_products.html (search by "schedule" word).

deployed to the integration environment and is being tested

**Comment by monkeypants** [comment]
@simon-tma can you confirm the as-documented behaviour meets your need?

> It's just missing the starting price.
> Could either use a special key (default?)
> or just have the price be 0 until the first scheduled value.

If today is before the first date in the price schedule, isn't the `cost_per_unit` is the "starting price". Do we really need a distinct starting price?

>  I'm assuming the POST/PATCH bodies will use the same structure.

do you mean include the `price_schedule` element? Agree that seems like a fair assumption. @koriaf can you please confirm (and update the doc if yes)

**Comment by simon-tma** [comment]
@monkeypants 

> If today is before the first date in the price schedule, isn't the cost_per_unit is the "starting price". Do we really need a distinct starting price?

If that is the case, it'll be fine. Just needs to be documented.

**Comment by koriaf** [comment]
I've updated the documentation a little to reflect that

**Comment by monkeypants** [comment]
@simon-tma can we close this ticket?

**Comment by simon-tma** [comment]
@monkeypants Yup
