### ISSUE TITLE
high volume GET slots

### ISSUE THREAD

**Issue by monkeypants** [gs-gs/parks-bce-integration-bookable-things#16]
Currently `GET /products/{product_id}/slots/?from={datetime}&until={datetime}` returns a paginated list of 10 slots. When the API user wants to retrieve a large number of slots (e.g. ~1000), this results in a large number of calls. We need to make it easier (less chatty, less calls) to retrieve a large number (1000+) of slots.

Suggestions:
* make default pagination 100 (rather than 10)
* make page size an optional parameter (so user can say `&pagesize=1000`) if that's what they want

Are there problems with this? Does the page size need to be small for performance/load reasons? How else could we meet this need?

**Comment by koriaf** [comment]
There is page_size parameter, the widget uses value "500". the only issue that it seems not to be documented which will be fixed.
I wonder how the widget developers found about it.

**Comment by monkeypants** [comment]
@simon-tma does this page_size parameter work for you?

**Comment by simon-tma** [comment]
This has definitely improved the speed when polling! Is working fine from here.

**Comment by monkeypants** [comment]
seems to be good enough
