### ISSUE TITLE
bulk slot creation

### ISSUE THREAD

**Issue by monkeypants** [gs-gs/parks-bce-integration-bookable-things#17]
We expect BCE to need to create something in the range of 5,000-7,000 new slots per week, and they need to create ~800,000 slots in bulk to configure the system as a once-off. Doing this with individual `POST /products/{product_id}/slots/` calls is annoyingly slow.

Suggestions:
* modify the POST to accept individual slots (as it does now) or list of them, perhaps with a reasonable limit (e.g 250 slots in a call - or whatever is reasonable to prevent gateway timeouts etc).
* make an asynchronous bulk endpoint, `POST /products/(product_id)/bulkslots/` that validates the input (error if invalid) but then processes them asynchronously (using a queue and worker). This would need a mechanism for sending errors back to the caller, it wouldn't be safe to let them assume it worked, and not all errors could be checked with a parser (i.e. not all errors could be checked synchronously). So maybe the `bulkslots` signature would need a callback API for errors?

Maybe the "modest list" could give a 100x reduction in calls, would be good enough?

**Comment by koriaf** [comment]
https://parks-australia-bookable-things.readthedocs.io/en/latest/api_slots.html#slot-create in the end

the validation is sync and I believe it's fine. The widget is already using it. One slot with error means no slots are created. There are no limits apart of the practical ones, I guess they should pick a number of slots giving you good balance between execution time and error possibility.

**Comment by monkeypants** [comment]
@simon-tma it looks like we already have this too :) can you check this?

**Comment by simon-tma** [comment]
This is working great. I don't see slots needing to be updated or deleted that often, so keeping those as individual calls should work fine.

**Comment by koriaf** [comment]
>  updated or deleted

when you need it just ask, and in 2-3 weeks it will be on production.

**Comment by monkeypants** [comment]
Assume this ship has sailed
